# Generated by Django 4.2.9 on 2024-02-04 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentDown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caller_id', models.CharField(max_length=200)),
                ('emailAdress', models.EmailField(blank=True, max_length=200, null='True')),
                ('description', models.TextField()),
                ('comments', models.TextField(blank=True, null='True')),
                ('impact', models.IntegerField(default=4)),
                ('urgency', models.IntegerField(default=4)),
                ('worknotes', models.TextField(blank=True, null='True')),
                ('assignment_group', models.CharField(blank=True, max_length=200, null='True')),
                ('state', models.IntegerField(default=1)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_process', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'SnowIncidentForm',
                'ordering': ['-date'],
            },
        ),
    ]
